apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
    project: guestbook2
    source:
        repoURL: https://github.com/cogitosun/guestbook2.git
        targetRevision: HEAD
        path: dev
        helm:
          parameters:
            - name: repoName
              value: guestbook2
            - name: imageVersion
              value: 1.0.0
            - name: deliveryVersion
              value: master
          valueFiles:
            - values/tools.yaml
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
        automated:
            prune: true
            selfHeal: false
