apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-delivery
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cogitosun/spring-delivery.git
    targetRevision: master
    path: .
    helm:
      parameters:
        - name: deliveryVersion
          value: master
      valueFiles:
        - values/dev.yaml
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false